### ISSUE TITLE
Discussion #1

### ISSUE THREAD

**Issue by ALEXMORF** [axvlad/eos#1]
1. Why are math functions Vector3Dot(), Vector3Cross(), and Vector3Normalize() not inlined?
2. Could we turn compiler warning up to -W4 -WX, that will help catch a lot of bugs and adds a lot of type safety. One thing that it would complain about is in Vector3Magnitude(), the sum is casted to double from float and the result of sqrt() is casted from double to float. In the future we should turn on these warnings to ensure C's coercion doesn't give us any nasty bugs. 

-W4 -WX are both flags for the compiler. -W4 means turning warning level to 4 and -WX means treat compiler warning as errors. If there are a warning to be disabled, add -wd[warning-id] to the options, where warning-id is the id of the warning to be disabled.

**Comment by axvlad** [comment]
1. Those should be inlined, good catch.
2. That's a good idea. I'll go ahead an do that with my compiler.
